### ISSUE TITLE
Stackage nightly test failure

### ISSUE THREAD

**Issue by lwm** [tebello-thejane/bitx.hs#4]
```
Failures:
  test/Network/Bitcoin/BitX/Spec/Specs/NetSpec.hs:24: 
  1) Network.Bitcoin.BitX.Spec.Specs.Net, 
       Public BitX connectivity, 
       getTrades connects to BitX and works
```

**Comment by tebello-thejane** [comment]
It would appear that the BitX/Luno API has been updated slightly (their currency pair list has been cleaned up).

I shall fix the package in a bit...

**Comment by tebello-thejane** [comment]
Fixed: 14ea41fd7e992a050686eb03a6c889519a8afa2a.

I will upload a package shortly.

**Comment by lwm** [comment]
Thanks @tebello-thejane! Please feel free to revert https://github.com/fpco/stackage/commit/5f72de2242a210c9969935374f2f7c66e0aed8a8 when your new version is on Hackage or just close this and I'll take care of it, as you want :beers:

**Comment by tebello-thejane** [comment]
Nah. Another issue has popped up. It seems as if their API is now much more severely rate-limited, so my rate-limiting scheme still often fails with HTTP 429 (especially with parallel Travis-ci runs). 

I will have to think deeply about how to work around this...

**Comment by tebello-thejane** [comment]
I pushed a fix a long time ago, but neglected to release. I'll alert Stackage once the fix is pushed.

**Comment by lwm** [comment]
> I'll alert Stackage once the fix is pushed.

Thanks!

**Comment by mithrandi** [comment]
@tebello-thejane I think we're ready for the release; anything I can help out with or is it just a matter of uploading to Hackage now?

**Comment by tebello-thejane** [comment]
New version finally uploaded: [bitx-bitcoin-0.12.0.0](https://hackage.haskell.org/package/bitx-bitcoin-0.12.0.0).

Fixes this issue, and a few others. Much thanks to @mithrandi. :smiley_cat:

**Comment by bergmark** [comment]
This is still failing on the stackage build server using 0.12.0.0:
```
Failures:

  test/Network/Bitcoin/BitX/Spec/Specs/NetSpec.hs:20:5:
  1) Network.Bitcoin.BitX.Spec.Specs.Net, Public BitX connectivity, getTickers connects to BitX and works

  To rerun use: --match "/Network.Bitcoin.BitX.Spec.Specs.Net/Public BitX connectivity/getTickers connects to BitX and works/"

Randomized with seed 400169759
```
